=== DenisAShmelev/denis.a.shmelev.github.io/Компоненты/Все компоненты из модели от 26.11.2022/attributes/TilePatternCatalog.dtd
<!-- The root element.  -->
<!ELEMENT TilePatternCatalog  (TilePattern*)>

<!-- 
    This element represents a single TilePattern. 
    A TilePattern must have HOffset and VOffset elements and at least one 
    Tile element. Parameter elements are optional.
-->
<!ELEMENT TilePattern (Parameter*, HOffset, VOffset, Color?, Tile+)>
<!ATTLIST TilePattern 
                Name CDATA #REQUIRED
                LinearUnit (MILLIMETER|CENTIMETER|METER|INCH|FOOT) "MILLIMETER"
                AngleUnit (RADIAN|DEGREE) "DEGREE"
>
<!-- 
    The ParameterName is an identifier, which can be used in equations just like
    the more general parameters.
-->

<!-- Horizontal Offset Vector -->
<!ELEMENT HOffset (Vector2D)>

<!-- Vertical Offset Vector -->
<!ELEMENT VOffset (Vector2D)>

<!-- 
    The default color is black. The integer values given in this element are default
    values. They can be changed in the dialog. Use space as the separator.
    Example: <Color Color="128 102 77" />
-->
<!ELEMENT Color EMPTY>
<!ATTLIST Color 
                Color CDATA "0 0 0"
>

<!-- 
    A Parameter is something you can use in the values of attributes of 
    all the elements in a TilePattern. The name of the Parameter is replaced
    with its value from the dialog and then the value of the attribute is 
    calculated.
-->
<!ELEMENT Parameter (Label)>
<!ATTLIST Parameter
        Name CDATA #REQUIRED
		UnitType (Length|Angle|Color) "Length"
		DefaultValue  CDATA #REQUIRED
>

<!-- 
     The content is first transcoded to local code page and then spaces and
     new lines are replaced with spaces. Then spaces are removed from the 
     beginning and the end of the string. 
-->
<!ELEMENT Label (#PCDATA)>

<!--
    Represents one tile in the pattern. The unit of the attributes is given
    in the attributes of the pattern.
-->
<!ELEMENT Tile (TileOrigin, Color?)>
<!ATTLIST Tile
		Angle     CDATA  #REQUIRED
		Width     CDATA  #REQUIRED
		Height    CDATA  #REQUIRED
		Thickness CDATA  #REQUIRED
>

<!ELEMENT TileOrigin (Vector2D)>

<!ELEMENT Vector2D EMPTY>
<!ATTLIST Vector2D
            X CDATA "0"
            Y CDATA "0"
>

=== DenisAShmelev/denis.a.shmelev.github.io/Компоненты/Все компоненты из модели от 26.11.2022/attributes/TilePatternCatalog.xml
<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<!DOCTYPE TilePatternCatalog SYSTEM "TilePatternCatalog.dtd">
<TilePatternCatalog>
	<TilePattern Name="1_1" LinearUnit="INCH">
		<Parameter Name="W" UnitType="Length" DefaultValue="11.75">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" UnitType="Length" DefaultValue="3.75">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="TH" UnitType="Length" DefaultValue="0.75">
			<Label> _Tile_Thickness </Label>
		</Parameter>
		<Parameter Name="MH" UnitType="Length" DefaultValue="0.5">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" UnitType="Length" DefaultValue="0.5">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<Parameter Name="TC" UnitType="Color" DefaultValue="204 178 153">
			<Label> _Tile_Color </Label>
		</Parameter>
		<Parameter Name="MC" UnitType="Color" DefaultValue="50 60 70">
			<Label> _Mortar_Color </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+MW" Y="0" />
		</HOffset>
		<VOffset>
			<Vector2D X="0" Y="H+MH" />
		</VOffset>
		<Color Color="MC" />
		<Tile Angle="0" Width="W" Height="H" Thickness="TH">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
	</TilePattern>
	<TilePattern Name="1_2">
		<Parameter Name="W" UnitType="Length" DefaultValue="200">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" UnitType="Length" DefaultValue="100">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="MH" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<Parameter Name="TC" UnitType="Color" DefaultValue="204 178 153">
			<Label> _Tile_Color </Label>
		</Parameter>
		<Parameter Name="MC" UnitType="Color" DefaultValue="50 60 70">
			<Label> _Mortar_Color </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+MW" Y="0" />
		</HOffset>
		<VOffset>
			<Vector2D X="0" Y="2*(H+MH)" />
		</VOffset>
		<Color Color="MC" />
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0.5*W" Y="H+MH" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
	</TilePattern>
	<TilePattern Name="1_3">
		<Parameter Name="W" UnitType="Length" DefaultValue="200">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" UnitType="Length" DefaultValue="100">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="MH" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<Parameter Name="TC" UnitType="Color" DefaultValue="204 178 153">
			<Label> _Tile_Color </Label>
		</Parameter>
		<Parameter Name="MC" UnitType="Color" DefaultValue="50 60 70">
			<Label> _Mortar_Color </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+MW" Y="0" />
		</HOffset>
		<VOffset>
			<Vector2D X="0" Y="2*(H+MH)" />
		</VOffset>
		<Color Color="MC" />
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0.33*W" Y="H+MH" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
	</TilePattern>
	<TilePattern Name="1_4">
		<Parameter Name="W" UnitType="Length" DefaultValue="200">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" UnitType="Length" DefaultValue="100">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="MH" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" UnitType="Length" DefaultValue="20">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<Parameter Name="TC" UnitType="Color" DefaultValue="204 178 153">
			<Label> _Tile_Color </Label>
		</Parameter>
		<Parameter Name="MC" UnitType="Color" DefaultValue="50 60 70">
			<Label> _Mortar_Color </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+MW" Y="0" />
		</HOffset>
		<VOffset>
			<Vector2D X="0" Y="2*(H+MH)" />
		</VOffset>
		<Color Color="MC" />
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
		<Tile Angle="0" Width="W" Height="H" Thickness="100">
			<TileOrigin>
				<Vector2D X="0.25*W" Y="H+MH" />
			</TileOrigin>
			<Color Color="TC" />
		</Tile>
	</TilePattern>
	<TilePattern Name="Herringbone">
		<Parameter Name="W" DefaultValue="180">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" DefaultValue="80">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="T" DefaultValue="100">
			<Label> _Tile_Thickness </Label>
		</Parameter>
		<Parameter Name="MH" DefaultValue="20">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" DefaultValue="20">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+2*H+3*MW" />
		</HOffset>
		<VOffset>
			<Vector2D Y="W+2*H+3*MW" />
		</VOffset>
		<Color Color="50 60 70" />
		<!-- Tile 1 -->
		<Tile Angle="0" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
		<!-- Tile 2 -->
		<Tile Angle="90" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="W" Y="H+MH" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
		<!-- Tile 3 -->
		<Tile Angle="90" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="W+H+MW" Y="0" />
			</TileOrigin>
			<Color Color="179 153 128" />
		</Tile>
		<!-- Tile 4 -->
		<Tile Angle="0" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="W+MW" Y="W+MH" />
			</TileOrigin>
			<Color Color="179 153 128" />
		</Tile>
		<!-- Tile 5 -->
		<Tile Angle="0" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="W+H+2*MW" Y="H+MH" />
			</TileOrigin>
			<Color Color="153 128 102" />
		</Tile>
		<!-- Tile 6 -->
		<Tile Angle="90" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="H" Y="2*(H+MH)" />
			</TileOrigin>
			<Color Color="153 128 102" />
		</Tile>
		<!-- Tile 7 -->
		<Tile Angle="90" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="W+2*(H+MW)" Y="W+H+2*MH" />
			</TileOrigin>
			<Color Color="128 102 77" />
		</Tile>
		<!-- Tile 8 -->
		<Tile Angle="0" Width="W" Height="H" Thickness="T">
			<TileOrigin>
				<Vector2D X="H+MW" Y="H+W+2*MH" />
			</TileOrigin>
			<Color Color="128 102 77" />
		</Tile>
	</TilePattern>
	<TilePattern Name="Basketweave">
		<Parameter Name="W" DefaultValue="220">
			<Label> _Tile_Width </Label>
		</Parameter>
		<Parameter Name="H" DefaultValue="100">
			<Label> _Tile_Height </Label>
		</Parameter>
		<Parameter Name="TH" DefaultValue="100">
			<Label> _Tile_Thickness </Label>
		</Parameter>
		<Parameter Name="MH" DefaultValue="20">
			<Label> _Mortar_Height </Label>
		</Parameter>
		<Parameter Name="MW" DefaultValue="20">
			<Label> _Mortar_Width </Label>
		</Parameter>
		<HOffset>
			<Vector2D X="W+2*H+3*MW" Y="0" />
		</HOffset>
		<VOffset>
			<Vector2D X="0" Y="W+MH" />
		</VOffset>
		<Tile Angle="0" Width="W" Height="H" Thickness="TH">
			<TileOrigin>
				<Vector2D X="0" Y="0" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
		<Tile Angle="0" Width="W" Height="H" Thickness="TH">
			<TileOrigin>
				<Vector2D X="0" Y="H+MH" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
		<Tile Angle="90" Width="W" Height="H" Thickness="TH">
			<TileOrigin>
				<Vector2D X="W+MW+H" Y="0" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
		<Tile Angle="90" Width="W" Height="H" Thickness="TH">
			<TileOrigin>
				<Vector2D X="W+2*(MW+H)" Y="0" />
			</TileOrigin>
			<Color Color="204 179 153" />
		</Tile>
	</TilePattern>
	<TilePattern Name="Checkered_Plate" LinearUnit="INCH">
		<Parameter Name="L" UnitType="Length" DefaultValue="1">
			<Label> _Pattern_Length </Label>
		</Parameter>
		<Parameter Name="W" UnitType="Length" DefaultValue=".125">
			<Label> _Pattern_Width </Label>
		</Parameter>
		<Parameter Name="T" UnitType="Length" DefaultValue=".5">
			<Label> _Plate_Thickness </Label>
		</Parameter>
		<Parameter Name="PS" UnitType="Length" DefaultValue=".25">
			<Label> _Pattern_Spacing </Label>
		</Parameter>
		<Parameter Name="BC" UnitType="Color" DefaultValue="200 200 200">
			<Label> _Background_Color </Label>
		</Parameter>
		<Parameter Name="PC" UnitType="Color" DefaultValue="100 100 100">
			<Label> _Pattern_Color</Label>
		</Parameter>
		<HOffset>
			<Vector2D X="L+2*PS+W" />
		</HOffset>
		<VOffset>
			<Vector2D Y="L+2*PS+W" />
		</VOffset>
		<Color Color="BC" />
		<!-- Tile 1 -->
		<Tile Angle="0" Width="L" Height="W" Thickness="T">
			<TileOrigin>
				<Vector2D X="0" Y="(L-W)*0.5" />
			</TileOrigin>
			<Color Color="PC" />
		</Tile>
		<!-- Tile 2 -->
		<Tile Angle="0" Width="W" Height="L" Thickness="T">
			<TileOrigin>
				<Vector2D X="L+PS" Y="0" />
			</TileOrigin>
			<Color Color="PC" />
		</Tile>
		<!-- Tile 3 -->
		<Tile Angle="0" Width="W" Height="L" Thickness="T">
			<TileOrigin>
				<Vector2D X="(L-W)*0.5" Y="(L+W)*0.5+PS" />
			</TileOrigin>
			<Color Color="PC" />
		</Tile>
		<!-- Tile 4 -->
		<Tile Angle="0" Width="L" Height="W" Thickness="T">
			<TileOrigin>
				<Vector2D X="(L+W)*0.5+PS" Y="L+PS" />
			</TileOrigin>
			<Color Color="PC" />
		</Tile>
	</TilePattern>
	<TilePattern Name="Expanded_Metal" AngleUnit="RADIAN">
		<Parameter Name="PW" UnitType="Length" DefaultValue="34">
			<Label> _Pattern_Width </Label>
		</Parameter>
		<Parameter Name="PL" UnitType="Length" DefaultValue="135.4">
